### ISSUE TITLE
v1.4 breaks support for non-QWERTY keyboard layout

### ISSUE THREAD

**Issue by fuzy112** [violentmonkey/vm-shortcut#14]
I am using the [DVORAK](https://en.wikipedia.org/wiki/Dvorak_keyboard_layout) keyboard layout and my script registers a shortcut `a-q`.  After upgrading @violentmonkey/shortcut to v1.4, my shortcut is not triggered when `Alt+Q` is pressed, but it is triggered when `Alt+'` is pressed. (On my keyboard, `'` is the key which would be `Q` on QWERTY keyboard.)

**Comment by gera2ld** [comment]
I think there is no way for us to capture `alt-` shortcuts when the keyboard layout is different, because all we have is `event.key` which does not work with `alt` well, and `event.code` which does not respect the keyboard layout.

I will remove the conversion of key names from `KeyQ` to `Q` so it is clearer which is being used, e.g. `a-keyq` for `event.code`, which means the physical `Q` key is pressed, while `c-q` for `event.key`, which means the key emits the letter `q`.

**Comment by gera2ld** [comment]
Could you help to verify it in https://violentmonkey.github.io/vm-shortcut/ ? Thanks.

**Comment by fuzy112** [comment]
It works now. Thanks.
