### ISSUE TITLE
Don't register shortcut when input field is focused

### ISSUE THREAD

**Issue by cunlem** [violentmonkey/vm-shortcut#6]
How can I achieve this? 

I see example given in README is incomplete as it lacks `isInput` function definition:

```js
// Only register the following key when `inputFocus` is false
service.register('g g', () => {
  console.log('Now inputFocus is false and you pressed `g g`');
}, {
  condition: '!inputFocus',
});

// Handle inputFocus using capture mode
document.addEventListener('focus', (e) => {
  if (isInput(e.target)) service.setContext('inputFocus', true);
}, true);
document.addEventListener('blur', (e) => {
  if (isInput(e.target)) service.setContext('inputFocus', false);
}, true);
```

**Comment by gera2ld** [comment]
https://github.com/violentmonkey/violentmonkey/blob/0fd1a0345ed95f76efabce86e94abd7273dc5b96/src/common/keyboard.js#L9-L11

**Comment by nexushoratio** [comment]
I'm a JS newbie.

How would I access this  `isInput()` function?

In particular, I'm writing a userscript and using `@require https://cdn.jsdelivr.net/npm/@violentmonkey/shortcut@1`.

Or do I just copy-and-paste that function into my script?

Actually, I already wrote my equivalent, but since I don't know what I'm doing, I also added a check for `el.isContentEditable`, if that matters.

**Comment by gera2ld** [comment]
@nexushoratio Please create a new issue with a demo.
